# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-f0.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-f1.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-f2.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-f3.dtb
#dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-f4.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-t0.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-t1.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lkd3588-p0.dtb

dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-f0.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-f1.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-f2.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-f3.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-f4.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpa3588-t0.dtb

dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpb3588-f0.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP)+= rk3588-neardi-linux-lpb3588-t0.dtb

