#define  MODEM_ENABLE_GPIO   	1
#define  HOST_WAKEUP_GPIO_IN 	2
#define  MODEM_WAKEUP_GPIO_OUT  3
#define  SEEKWAVE_NV_NAME  "SEEKWAVE_NV_SWT6652.bin"
#define  SKW_IRAM_FILE_PATH  "/data/ROM_EXEC_KERNEL_IRAM.bin"
#define  SKW_DRAM_FILE_PATH  "/data/RAM_RW_KERNEL_DRAM.bin"
